=== desibankproject/soapwebservice-bu/src/main/webapp/fruits.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.fresh.com/fruits"
	xmlns:tns="http://www.fresh.com/fruits" elementFormDefault="qualified">
	<element name="fruits" type="tns:Fruits"/>	
	<!-- 
	  class Fruits{
	    List<Fruit> fruit;
	  }
	 -->
	<complexType name="Fruits">
			<sequence>
				<element name="fruit" type="tns:Fruit" minOccurs="0" maxOccurs="3"/>			
			</sequence>
	</complexType>
	
	<!-- 
	 class Fruit {
	 	String name;
	 }
	 -->
	<complexType name="Fruit">
			<sequence>
				 		<element name="name" type="string"/>			
						 <element name="color" type="string"/>
				 		<element name="price" type="int"/>
			</sequence>
	</complexType>
</schema>

=== desibankproject/soapwebservice-bu/src/main/webapp/fruits.xml
<?xml version="1.0" encoding="UTF-8"?>
<fruits xmlns="http://www.fresh.com/fruits"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.fresh.com/fruits fruits.xsd ">
	<fruit>
		<name>Apple</name>
		<color>Red</color>
		 <price>133</price>	
	</fruit>
	<fruit>
		<name>Mango</name>
		<color>Yellow</color>
		 <price>234</price>	
	</fruit>
	
	<fruit>
		<name>Guava</name>
		<color>Yellow</color>
		 <price>234</price>	
	</fruit>
</fruits>
